### ISSUE TITLE
I'm seeing horizontal and vertical scrollbars for what seems like a hero page

### ISSUE THREAD

**Issue by MJez29** [Yeliang-Radish/Personal-Website#2]
You may want to add
```css
body {
  overflow: hidden;
}
```
